bind C-r source-file ~/.tmux.conf \; display "reloaded config"

# proper colors in kitty
set -g default-terminal "tmux-256color"

# mouse to scroll/resize splits
set -g mouse on

# window/pane numbering starts at 1
set -g base-index 1
setw -g pane-base-index 1

# renumber windows when one is closed
set -g renumber-windows on

# longer scroll history
set -g history-limit 100000

# apparently this fixes the escape delay in vim
set -sg escape-time 0

# clipboard stuff ("dangerous" but i would simply not run such commands)
set -g set-clipboard on
set -g allow-passthrough on

# better splits (yes, these are backwards compared to tmux's terminology)
unbind %
bind v split-window -h
unbind \"
bind s split-window -v

# better window/pane navigation
unbind Up
unbind Down
unbind Left
unbind Right
bind Left previous-window
bind Right next-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# better create/delete
unbind x
bind q kill-pane
unbind c
bind t new-window
